sklearn.model_selection:

  GridSearchCV:
    scoring: "recall"
    n_jobs: -1
    cv: None
    verbose: 1

  RandomizedSearchCV:
    scoring: "recall"
    n_iter: 10
    n_jobs: -1
    cv: None
    verbose: 1