modules/:
  training_modules/:

    base_trainer.py:
      searchCV:
        n_jobs: -1
        cv: 5
        verbose: 3
        n_iter: 10

    classification.py:

      random_state: 42
      scoring: "accuracy"

      param_grids:
        LogisticRegression: 
          C: [0.1, 1, 10]
          solver: ["liblinear", "lbfgs"]             

        RandomForestClassifier: 
          n_estimators: [100, 200, 300, 500]
          max_depth: [5, 10, 15]
          min_samples_split: [2, 5, 10]
          min_samples_leaf: [1, 2, 4]
          max_features: ["sqrt", "log2", None]
          bootstrap: [True, False]
        
        LinearSVC:
          C: [0.01, 0.1, 1, 10, 100]
          max_iter: [1000, 5000, 10000]
          dual: [True, False]
        
        GaussianNB: 
          var_smoothing: [0.0000000010, 0.0000000100, 0.0000001000]        # [1e-9, 1e-8, 1e-7] Fix this error