data:
  random_state: 42
  test_size: 0.2
  input_path: "data/raw/sms_spam.csv"  # Đường dẫn dữ liệu gốc
  processed_path: "data/processed/cleaned_sms.csv"  # Đường dẫn dữ liệu đã xử lý

preprocessing:
  remove_stopwords: True
  lowercase: True
  remove_punctuation: True
  vectorization:
    method: "tfidf"  # Hoặc "count"
    max_features: 5000

training:
  model_type: "RandomForestClassifier"  # Thay đổi thành "LogisticRegression", "LinearSVC", hoặc "GaussianNB"
  scoring: "accuracy"
  cross_validation_folds: 5
  save_model_path: "models/spam_classifier.pkl"  # Đường dẫn lưu mô hình

hyperparameters:
  LogisticRegression:
    C: [0.1, 1, 10]
    solver: ["liblinear", "lbfgs"]

  RandomForestClassifier:
    n_estimators: [100, 200]
    max_depth: [5, 10]

  LinearSVC:
    C: [0.01, 0.1, 1]
    dual: [True, False]

  GaussianNB:
    var_smoothing: [1.0e-9, 1.0e-8]

prediction:
  load_model_path: "models/spam_classifier.pkl"  # Đường dẫn mô hình để dự đoán
  output_path: "data/processed/predictions.csv"  # Đường dẫn lưu kết quả dự đoán

api:
  host: "127.0.0.1"
  port: 5000
  debug: True

logging:
  level: "INFO"
  log_file: "logs/pipeline.log"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

testing:
  test_data_path: "data/processed/test_data.csv"
  expected_output_path: "data/processed/expected_output.csv"
