# Configuration of the run_pipeline.py file
run_pipeline.py:
  save_model:
  load_model:
  save_gridsearch:
  load_gridsearch:


# Configuration of the train_model.py file
train_model.py:
  save_model:
  save_gridsearch: