site_name: My Docs
repo_url: https://github.com/tranngoctai1010/Spam-Detector-ML

theme:
  name: material
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    menu: material/view-dashboard  # Icon menu nhìn chuyên nghiệp hơn (bảng điều khiển)
  logo: assets/logo.png  # Logo custom (bạn có thể dùng ảnh PNG/SVG)
  favicon: assets/favicon.png
  features:
    - content.code.copy # Thêm nút copy code
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: amber

    # Light mode
    - scheme: default
      toggle: 
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: pink

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]  # Để MkDocs tìm thấy `my_module.py`
          options:
            docstring_style: google
            members_order: source
            show_source: true
            heading_level: 2
            group_by_category: false  # Tắt nhóm thành bảng
            show_root_heading: true
            show_root_full_path: false
            show_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            show_root_toc_entry: false
            show_bases: true
            show_source_link: true
            separate_signature: true  # Tách chữ ký hàm
            show_category_heading: false  # Không thêm tiêu đề danh mục tự động
            # Vô hiệu hóa bảng:
            line_length: 0  # Ngăn markdown bị format thành bảng

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      pygments_style: monokai
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition

  - pymdownx.tabbed:
      alternate_style: true  # Căn chỉnh đúng mức thụt lề
  - toc:
      permalink: true  # Hiển thị link cố định cho từng mục lục
      title: "Table of Contents"
      toc_depth: 4

extra:
  generator: false  # Ẩn "Made with MkDocs"
  social:
    - icon: material/file-document-outline
      link: https://yourwebsite.com 

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - API Reference:
    - Factory:
      - Dynamic import: auto_ml/dynamic_import.md
      # - Utils:
      #   - Model handler: api/utils/model_handler.md
      #   - Logger manager: api/utils/logger_manager.md
      #   - Exception handler: api/utils/exception_handler.md