site_name: My Docs
repo_url: https://github.com/tranngoctai1010/Spam-Detector-ML

theme:
  name: material
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    menu: material/view-dashboard  # Icon menu nhìn chuyên nghiệp hơn (bảng điều khiển)
  logo: assets/logo.png  # Logo custom (bạn có thể dùng ảnh PNG/SVG)
  favicon: assets/favicon.png
  features:
    - content.code.copy # Thêm nút copy code
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: amber

    # Light mode
    - scheme: default
      toggle: 
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: pink

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]  # Để MkDocs tìm thấy `my_module.py`
          options:
            docstring_style: google
            members_order: source
            show_source: false
            heading_level: 2
            group_by_category: true
            show_root_heading: true
            show_root_full_path: false
            show_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            show_root_toc_entry: false
            show_bases: true
            show_source_link: true
            # source_link_path: "https://github.com/your-username/your-repo/blob/main/project/models.py"
            show_category_heading: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      pygments_style: monokai
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  
  - pymdownx.tabbed:
      alternate_style: true  # Căn chỉnh đúng mức thụt lề
  - toc:
      permalink: true  # Hiển thị link cố định cho từng mục lục
      title: "Table of Contents"
      toc_depth: 4

extra:
  generator: false  # Ẩn "Made with MkDocs"
  social:
    - icon: material/file-document-outline
      link: https://yourwebsite.com 

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  # - Structure: structure.md
  - Test: api/src/models/classifiers/random_forest.md
  - Evaluation:
      - Classification Report: api/evaluation/classification_report.md
  - API Reference: 
      - Utils:
        - Model handler: api/utils/model_handler.md
        - Logger manager: api/utils/logger_manager.md
        - Exception handler: api/utils/exception_handler.md













# site_name: My Docs
# repo_url: https://github.com/tranngoctai1010/Spam-Detector-ML

# theme:
#   name: material
#   font: 
#     text: Merriweather Sans
#     code: Red Hat Mono
#   icon:
#     menu: material/view-dashboard
#   logo: assets/logo.png
#   favicon: assets/favicon.png
#   features:
#     - navigation.path  # Bật thanh điều hướng
#     - content.code.copy
#   palette:
#     - scheme: slate
#       toggle:
#         icon: material/weather-sunny
#         name: Switch to light mode
#       primary: teal
#       accent: amber
#     - scheme: default
#       toggle: 
#         icon: material/weather-night
#         name: Switch to dark mode
#       primary: indigo
#       accent: pink

# plugins:
#   - search
#   - mkdocstrings:
#       handlers:
#         python:
#           paths: [".."]
#           options:
#             show_source: false
#             show_root_heading: true
#             show_root_full_path: false
#             show_signature: true
#             show_signature_annotations: true
#             merge_init_into_class: true
#             docstring_style: numpy  # Dùng chuẩn NumPy
#             docstring_section_style: list  # Hiển thị Parameters dưới dạng danh sách
#             show_root_toc_entry: false
#             show_bases: true
#             show_source_link: true
#             source_link_path: "https://github.com/tranngoctai1010/Spam-Detector-ML/blob/main/project/models.py"
#             show_category_heading: false
#             members_order: source

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#       linenums: true
#       pygments_style: monokai
#   - pymdownx.superfences
#   - tables
#   - admonition
#   - pymdownx.tabbed:
#       alternate_style: true
#   - toc:
#       permalink: true
#       title: "Table of Contents"
#       toc_depth: 4

# extra:
#   generator: false
#   social:
#     - icon: material/file-document-outline
#       link: https://yourwebsite.com

# extra_css:
#   - css/extra.css

# nav:
#   - Home: index.md
#   - API Reference:
#       - Test: api/src/models/classifiers/random_forest.md
#       - Evaluation:
#           - Classification Report: api/evaluation/classification_report.md
#       - Utils:
#           - Model Handler: api/utils/model_handler.md
#           - Logger Manager: api/utils/logger_manager.md
#           - Exception Handler: api/utils/exception_handler.md